version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: quirky-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: quirky_user
      POSTGRES_PASSWORD: quirky_pass
      POSTGRES_DB: quirkydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
